import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Fragment } from 'react';
import LessonMenu from './LessonMenu';
import { Box } from '@mui/material';
import ReactVideoPlayer from '@/src/components/ReactVideoPlayer';

const LessonPage = ({ lesson, lessons }) => {

  let videoOptions = {
    controls : true,
    sources : [{
      src : lesson.url,
      type : 'video/mp4'
    }]
  }

  return (
    <>
      <Head>
        <title> DVF - קורס עריכת וידאו בכדורגל - {lesson.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box >
        <Box>
          <LessonMenu lessons={lessons} />
        </Box>
        <Box sx={{ margin : 'auto' }}>
          <h2 style={{ textAlign : 'center' , color : '#ffa22d' }}>{lesson.title}</h2>
          <Box sx={{ justifyContent: 'center', display: 'flex' }}>
          { console.log(lesson.url) }
          <ReactVideoPlayer options={videoOptions}/>
          </Box>
          <Box sx={{ justifyContent: 'center', display: 'flex', textAlign: 'center' }}>
          {
            lesson.description &&
            <p style={{ color : '#FFF' }}>{lesson?.description.split('\n').map((line, index) => (
              <Fragment key={index}>
                {line}
                <br />
              </Fragment>
            ))}</p>
          }
          </Box>
        </Box>
      </Box>
    </>
  );
};

export async function getServerSideProps({ req, params }) {
  const host = `${req.headers['x-forwarded-proto']}://${req.headers['host']}`;
  const { id } = params;
  const response = await axios.get(`${host}/api/lessons/${id}`);
  const lesson = response.data;

  // Fetch the lessons data from your API
  const lessonsResponse = await axios.get(`${host}/api/lessons`);
  const lessons = lessonsResponse.data;

  return {
    props: {
      lesson,
      lessons,
    },
  };
}

export default LessonPage;
