import axios from 'axios';
import Head from 'next/head';
import { Fragment } from 'react';
import LessonMenu from './LessonMenu';
import { Box } from '@mui/material';
import AccordionComp from '@/src/components/AccordionComp';
import AttachFileIcon from '@mui/icons-material/AttachFile';
import { CssButton } from '@/src/components/Custom Button';

const LessonPage = ({ lesson, lessons }) => {

  const downloadFile = (file) => {
    if(file) {
      const link = document.createElement('a');
      link.href = file;
      link.download = true;
      link.click();
    }
  };

  return (
    <>
      <Head>
        <title> DVF - קורס עריכת וידאו בכדורגל - {lesson.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Box>
          <LessonMenu lessons={lessons} />
        </Box>
        <Box sx={{ margin : 'auto' , width : '800px' }}>
          <h2 style={{ textAlign : 'center' , color : '#ffa22d' }}>{lesson.title}</h2>
          <Box sx={{ justifyContent: 'center', display: 'flex', textAlign: 'center' }}>
          {
            lesson.description &&
            <p style={{ color : '#FFF' }}>{lesson?.description.split('\n').map((line, index) => (
              <Fragment key={index}>
                {line}
                <br />
              </Fragment>
            ))}</p>
          }
          </Box>
          {
            lesson.bullets.length > 0 &&
            <AccordionComp lesson={lesson}/>
          }
          <Box sx={{ display: 'flex', justifyContent: 'end' }}>
            {
                lesson.file &&
                <Box sx={{textAlign: 'end' , margin : '0rem 0.3rem'}}>
                  <CssButton onClick={() => downloadFile(lesson.file)} startIcon={<AttachFileIcon />}>הורדת אפקטים</CssButton>
                </Box>
            }
            {
                lesson.fileMac &&
                <Box sx={{textAlign: 'end'}}>
                  <CssButton onClick={() => downloadFile(lesson.fileMac)} startIcon={<AttachFileIcon />}>הורדת אפקטים  MAC</CssButton>
                </Box>
            }
          </Box>
          <Box sx={{ justifyContent: 'center', display: 'flex' }}>
          <video src={lesson.url} width={800} controls controlsList="nodownload"/>
          </Box>
          
        </Box>
      </Box>
    </>
  );
};

export async function getServerSideProps({ req, params }) {
  const host = `${req.headers['x-forwarded-proto']}://${req.headers['host']}`;
  const { id } = params;
  const response = await axios.get(`${host}/api/lessons/${id}`);
  const lesson = response.data;

  // Fetch the lessons data from your API
  const lessonsResponse = await axios.get(`${host}/api/lessons`);
  const lessons = lessonsResponse.data;

  return {
    props: {
      lesson,
      lessons,
    },
  };
}

export default LessonPage;
