import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import LessonMenu from "./lessons/LessonMenu";
import LessonPage from "./lessons/[id]";
import { Box } from "@mui/material";

const Lessons = ({ lessons }) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>DVF - קורס עריכת וידאו בכדורגל - שיעורי הקורס</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lesson-page">
        <div className="lesson-menu">
          <LessonMenu lessons={lessons} />
        </div>
        <div className="lesson-content">
          {router.query.lessonId ? (
            <LessonPage lessonId={router.query.lessonId} />
          ) : (
            <Box sx={{ width: "800px", margin: "auto" }}>
              <p
                style={{
                  color: "#fff",
                  textAlign: "center",
                  fontSize: "1.5rem",
                }}
              >
                ברוכים הבאים לקורס,
                <br />
                אני מאוד שמח שבחרת להכנס למסע הזה ובחרת בי,
                <br />
                אני בטוח שבשיעור האחרון לאחר שתתרגל/י את מה שלמדת כאן יהיה לך
                ערך מוסף בתעשיה.
                <br />
              </p>
            </Box>
          )}
        </div>
      </div>
    </>
  );
};

export async function getServerSideProps({ req }) {
  const host = `${req.headers["x-forwarded-proto"]}://${req.headers["host"]}`;
  const response = await axios.get(`${host}/api/lessons`);
  const lessons = response.data;
  return {
    props: {
      lessons,
    },
  };
}

export default Lessons;
