import CustomLoadingButton from '@/src/components/Custom Button Loading'
import CustomField from '@/src/components/Custom Field'
import CustomFieldWithShowPass from '@/src/components/Custom Field showPass'
import { Box, Button } from '@mui/material'
import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { toast } from 'react-hot-toast'

const Register = () => {
  const [invitation, setInvitation] = useState('')
  const [invitationExist, setInvitationExist] = useState(false)
  const [user, setUser] = useState({ email : "" , phoneNumber : "" , fName : "" , lName : '' , confirmPassword : "" , password : "" })
  const router = useRouter();

  const handleSubmit = async (e) => {
    e.preventDefault();
  
    toast.promise(
      new Promise(async (resolve, reject) => {
        try {
          const resp = await axios.post('api/auth', { user, invitation });
          if (resp.data.success) {
            setInvitation('');
            router.push('/');
          }
          resolve();
        } catch (error) {
          reject(error.response.data.message);
        }
      }),
      {
        loading: 'כמה רגעים...',
        success: 'בוצע בהצלחה !',
        error: (error) => {
          console.log(error);
          return error
        },
      }
    );
  };
  
  
  const checkInvitation = async (e) => {
    e.preventDefault()
      toast.promise(
        new Promise(async (resolve, reject) => {
          try {
            const resp = await axios.get(`api/Invitation/${invitation}`);
            if(resp.data.success) {
              setInvitationExist(true)
            } else {
              setInvitationExist(false)
            }
            resolve();
          } catch (error) {
            reject(error.response.data.message);
          }
        }),
        {
          loading: 'כמה רגעים...',
          success: 'בוצע בהצלחה !',
          error: "אין אסימון כזה !",
        }
      );
  }

  const checkForm = () => {
    if (!user.email || !user.fName || !user.lName || !user.phoneNumber || !user.password || !user.confirmPassword) {
      return true;
    }
    if (user.password !== user.confirmPassword) {
      return true;
    } else {
      return false;
    }
  };
  
  useEffect(() => {
    const token = localStorage.getItem('token');
    if (token) {
      router.push('/');
    }
  }, [router]);

  return (
    <>
    <Head>
        <title>DVF - קורס עריכת וידאו בכדורגל - הרשמה</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Box sx={{ textAlign: 'center', padding: '3rem' }}>
        <h1 style={{ color : '#ffa22d' }}>הגדרת משתמש</h1>
        {
          invitationExist ? 
          <Box component="form" onSubmit={handleSubmit} sx={{ width: { md : '30%' , xs : '100%' }, margin: 'auto' }}>
        <CustomField required value={ user.fName || "" } label="שם פרטי" onChange={e => setUser({...user, fName : e.target.value})} fullWidth/>
        <CustomField required value={ user.lName || "" } label="שם משפחה" onChange={e => setUser({...user, lName : e.target.value})} fullWidth/>
        <CustomField required req value={ user.email || "" } type="email" label="דואר אלקטרוני" onChange={e => setUser({...user, email : e.target.value})}  fullWidth/>
        <CustomField required value={ user.phoneNumber || "" } label="מספר טלפון" onChange={e => setUser({...user, phoneNumber : e.target.value})}  fullWidth/>
        <CustomFieldWithShowPass required value={ user.password || "" } label="סיסמה" onChange={e => setUser({...user, password : e.target.value})}  fullWidth/>
        <CustomFieldWithShowPass required value={ user.confirmPassword || "" } label="אישור סיסמה" onChange={e => setUser({...user, confirmPassword : e.target.value})}  fullWidth/>
        <Link href='sign-in' style={{ color: '#FFFF', textDecoration: 'none', float: 'right', margin: '0.5rem' }}>משתמש מוגדר? לחץ כאן</Link>
        <CustomLoadingButton disabled={checkForm() ? true : false} type="submit" value="הפעלת חשבון" width="100%"/>
        </Box>
          :
          <Box component="form" onSubmit={checkInvitation} sx={{ width: { md : '30%' , xs : '100%' }, margin: 'auto' }}>
          <CustomField label="הזמנה" onChange={e => setInvitation(e.target.value)} fullWidth/> 
            <Link href='sign-in' style={{ color: '#FFFF', textDecoration: 'none', float: 'right', margin: '0.5rem' }}>משתמש מוגדר? לחץ כאן</Link>
            <CustomLoadingButton type="submit" value="בדיקת אסימון" width="100%"/>
          </Box>
        }

        
    </Box>
    </>
  )
}

export default Register